### ISSUE TITLE
rendering failure on iTerm2

### ISSUE THREAD

**Issue by cdornan** [NorfairKing/safe-coloured-text#10]
iTerm2 (3.4.23) fails to parse some CSI parameters when a '0' is squashed. I have some code that isolates the issue [here](https://github.com/cdornan/bug-report-safe-coloured-text/blob/main/app/sct-issue.hs).

Could we forgo the zero-squashing considering it won't yield much compression in this flabby encoding? Or at least provide it as an option? (I will raise a PR for simply killing the 0 squashing to help get things going.)

**Comment by cdornan** [comment]
My experiments showed much the same &mdash; the few that supported full 24-bit colour tended to work with the empty parameters. But iTerm2 is _the_ Mac terminal app for devs so it breaks Macs.

I have submitted a minimal PR that fixes the issue for iTerm2 but it does not address the tests -- it is just an illustrative starting point really.

**Comment by NorfairKing** [comment]
Fixed with https://hackage.haskell.org/package/safe-coloured-text-0.2.0.2
