### ISSUE TITLE
Cross-compilation with terminfo

### ISSUE THREAD

**Issue by notquiteamonad** [NorfairKing/safe-coloured-text#2]
I've been using this library as part of [TIE](https://github.com/notquiteamonad/tie).

I've recently been trying to use haskell.nix to cross-compile for static builds using musl and windows builds. It's my first time using haskell.nix so this could just be my lack of experience causing issues but my cross-compiled builds are all failing at the terminfo dependency with the following:

```plaintext
Setup: Encountered missing or private dependencies:
terminfo -any
```

The nix expression I'm using to build this is here: https://github.com/notquiteamonad/tie/blob/haskell.nix/release/linux.nix

You say in the README that the terminfo dependency could be factored out - I assume by assuming minimal colour capabilities on the terminal as you use in the case of `Nothing` values. is this something I should look into providing a fork for or are there other ways of approaching this such as cabal flags that'd be more appropriate?

**Comment by NorfairKing** [comment]
Hi @notquiteamonad ! `haskell.nix`'s throwing their hands in the air at cross-compiling with `terminfo` is why I stopped using it: https://github.com/input-output-hk/haskell.nix/issues/919

We can factor out a separate package that can guess the `TerminalCapabilities` based on terminfo.
We can call it `safe-coloured-text-terminfo`. In that case you'd have to decide for yourself how many colours to output. I'll welcome a PR to do this. it should be quite easy, so please ping me if it ends up not being easy.

**Comment by notquiteamonad** [comment]
Cheers, I'll have a crack at that this afternoon and let you know when I have something to show

**Comment by NorfairKing** [comment]
Super! I'm happy that this ends up happening!
