### ISSUE TITLE
Update nixpkgs

### ISSUE THREAD

**Issue by srid** [NorfairKing/safe-coloured-text#4]
The nixpkgs used by this repo needs an update, so we can get GHC 9.2.1.

Currently hitting this strange error whenever I update nixpkgs

<img width="971" alt="image" src="https://user-images.githubusercontent.com/3998/152878989-fff2e663-8118-45da-a57c-dffcdec1fd5c.png">

**Comment by srid** [comment]
It is coming from sydtest overlay, as disabling it resolves it.

**Comment by srid** [comment]
`autodocodec` has the same issue.

**Comment by NorfairKing** [comment]
This isvolves a patch that used to be in `sydtest` but has since been upstreamed.
`niv update sydtest` should fix this.

**Comment by srid** [comment]
Yup, I confirm that it fixes it.
