### ISSUE TITLE
`safe-coloured-text-layout` broken on NixPkgs

### ISSUE THREAD

**Issue by peterbecich** [NorfairKing/safe-coloured-text#9]
`safe-coloured-text-layout` is marked broken on both `master` and `haskell-updates`:

```
nix build nixpkgs#haskellPackages.safe-coloured-text-layout

nix build nixpkgs/haskell-updates#haskellPackages.safe-coloured-text-layout
```

This also breaks `haskellPackages.feedback` on `nixpkgs`. I realize `feedback` is also available here: https://github.com/NorfairKing/feedback?tab=readme-ov-file#install-globally

The only issue are failing tests, and all of the failures are `golden output not found`:
```
.
.
.
  ✗ 6 Text.Colour.LayoutSpec.layoutAsTable.outputs this weird two-column table the same as before
      Retries: 3 (does not look flaky)
      Golden output not found
  
 
  Examples:                     18
  Passed:                       0
  Failed:                       6
  Sum of test runtimes:         0.01 seconds
  Test suite took:              0.00 seconds
 ```

Is Nix not finding these `dat` files?
https://github.com/NorfairKing/safe-coloured-text/blob/b8f83cfb47ed6ada2da2d55979cf2b7dd3867b2f/safe-coloured-text-layout/safe-coloured-text-layout.cabal#L19-L25
I would think `extra-source-files` would handle that issue.

Thanks

------

`safe-coloured-text-gen` is not broken; will be fixed shortly: https://github.com/NixOS/nixpkgs/pull/294814

**Comment by NorfairKing** [comment]
@peterbecich Maybe the version that's broken is not the version in nixpkgs?

**Comment by peterbecich** [comment]
I have tested the versions on `unstable` (I think from NixPkgs `master` branch) and `haskell-updates` branch; both are marked broken.

On the `haskell-updates` branch, I have unbroken the package to show the actual error. These errors are all `Golden output not found`.

**Comment by peterbecich** [comment]
This should show the real errors (`golden output not found`) on NixPkgs `unstable`:
```
NIXPKGS_ALLOW_BROKEN=1 nix build nixpkgs#haskellPackages.safe-coloured-text-layout --impure
```

**Comment by NorfairKing** [comment]
@peterbecich Thanks for the repro, that's exactly what I need.

But are you sure that the version that's on nixpkgs is indeed the version that's on master here?
If not, all we need is a new release with the right `extra-source-files`'s version that's already on master.

**Comment by NorfairKing** [comment]
@peterbecich I think if you update to the most recent version (`0.1.0.0`) of `safe-coloured-text-layout`, this will be fixed.

**Comment by peterbecich** [comment]
Thanks, apologies for not following up. It should be fixed on NixPkgs when the `all-cabal-hashes` pin is updated: https://github.com/NixOS/nixpkgs/blob/9d2be584a153a489e8a4d0fdba4baec9bf36e804/pkgs/data/misc/hackage/pin.json#L5

**Comment by NorfairKing** [comment]
@peterbecich Feel free to ping me if something else breaks. I'm pretty available when it comes to fixing my own stuff.
